"""FFIs not bound to any typeclass method — internal lifecycle / helper symbols."""

from .._entry import Entry


ENTRIES = {
    "idrisml_seq": Entry(args=("R", "R"), ret="R"),
    "param_register_return": Entry(args=("s", "T"), ret="T"),
    "param_tensor": Entry(args=("i",), ret="T"),
    "tensor_backward_conditional": Entry(args=("T",), ret="i"),
    "tensor_backward_return_loss": Entry(args=("T", "d"), ret="d"),
    "tensor_backward_return": Entry(args=("T",), ret="T"),
    "tensor_batch": Entry(args=("R", "i"), ret="T"),
    "tensor_bmm_3x3": Entry(args=("T", "T"), ret="T"),
    "tensor_cast_dtype_streamed": Entry(args=("T", "i", "i"), ret="T"),
    "tensor_cat_from_array": Entry(args=("R", "i", "i"), ret="T"),
    "tensor_causal_mask": Entry(args=("i",), ret="T"),
    "tensor_conv_transpose1d": Entry(args=("T", "T", "T", "i", "i"), ret="T"),
    "tensor_conv_transpose2d": Entry(args=("T", "T", "T", "i", "i", "i", "i"), ret="T"),
    "tensor_conv1d_grouped": Entry(args=("T", "T", "T", "i", "i", "i"), ret="T"),
    "tensor_conv2d_grouped": Entry(args=("T", "T", "T", "i", "i", "i", "i", "i"), ret="T"),
    "tensor_create_1d": Entry(args=("i", "R", "i"), ret="T"),
    "tensor_create_2d": Entry(args=("i", "i", "R", "i"), ret="T"),
    "tensor_create_param_1d": Entry(args=("i", "R"), ret="T"),
    "tensor_create_param_2d": Entry(args=("i", "i", "R"), ret="T"),
    "tensor_create_param_3d": Entry(args=("i", "i", "i", "R"), ret="T"),
    "tensor_create_param_4d": Entry(args=("i", "i", "i", "i", "R"), ret="T"),
    "tensor_create_state_1d": Entry(args=("i", "R"), ret="T"),
    "tensor_create_state_2d": Entry(args=("i", "i", "R"), ret="T"),
    "tensor_cross_entropy": Entry(args=("T", "T"), ret="T"),
    "tensor_device": Entry(args=("T",), ret="s"),
    "tensor_dim": Entry(args=("T",), ret="i"),
    "tensor_grad": Entry(args=("T",), ret="T"),
    "tensor_group_norm": Entry(args=("T", "T", "T", "i", "i", "i", "d"), ret="T"),
    "tensor_lstm_cell": Entry(args=("T", "T", "T", "T", "T", "T", "T", "R", "R"), ret="v"),
    "tensor_lstm_gates": Entry(args=("T", "T", "i", "R", "R"), ret="v"),
    "tensor_max": Entry(args=("T",), ret="T"),
    "tensor_min": Entry(args=("T",), ret="T"),
    "tensor_mse_loss": Entry(args=("T", "T"), ret="T"),
    "tensor_numel": Entry(args=("T",), ret="i"),
    "tensor_pair_free": Entry(args=("R",), ret="v"),
    "tensor_print": Entry(args=("T",), ret="v"),
    "tensor_ptr_array_set_return": Entry(args=("R", "i", "T"), ret="R"),
    "tensor_ptr_array_set": Entry(args=("R", "i", "T"), ret="v"),
    "tensor_reshape": Entry(args=("T", "R", "i"), ret="T"),
    "tensor_size": Entry(args=("T", "i"), ret="i"),
    "tensor_stack_from_array": Entry(args=("R", "i", "i"), ret="T"),
    "tensor_subtract_scalar_inplace": Entry(args=("T", "d"), ret="T"),
    "tensor_swiglu_2d": Entry(args=("T", "T"), ret="T"),
    "tensor_to_device": Entry(args=("T", "s"), ret="T"),
    "tensor_to_doubles": Entry(args=("T", "R"), ret="v"),
    "tensor_unbatch": Entry(args=("T", "R"), ret="R"),
    "tensor_zero_grad": Entry(args=("T",), ret="v"),
}
