#!/usr/bin/env python3
"""Generate packages/backends/rename_<backend>.h files.

For each built-in backend (tape, torch, mlx), this script writes a header
of `#define <sym> <sym>_<backend>` lines, one per exported C function
declared in `packages/backends/backend.h`. Injected into each backend's
compile command via `-include rename_<backend>.h` so the resulting `.o`
exports backend-suffixed symbols. Enables multi-link (all three
backends co-existing in one `libidrisml.(so|dylib)`) per the pluggable-
Device refactor's Phase 1.

Idempotent — re-running with no changes produces no diff. CI gates on
that property so the headers stay in sync as we add ops.

Usage:
    python3 scripts/gen-rename-headers.py [--check]

`--check` exits non-zero if the headers on disk differ from what we
would generate. Used by CI.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
BACKEND_H = REPO_ROOT / "packages" / "backends" / "backend.h"
OUT_DIR = REPO_ROOT / "packages" / "backends"

BACKENDS = ("tape", "torch", "mlx")

# Match C function declarations with a small but explicit set of return
# types. Anything more permissive risks catching macros / typedefs /
# struct members. Keep the type set aligned with what `backend.h`
# actually uses.
RETURN_TYPES = (
    r"TensorHandle\s*\*",  # TensorHandle*
    r"TensorHandle",
    r"TensorPair",
    r"const\s+char\s*\*",
    r"char\s*\*",
    r"void\s*\*",
    r"void",
    r"double",
    r"float",
    r"int",
)
RETURN_RE = r"(?:" + r"|".join(RETURN_TYPES) + r")"

DECL_RE = re.compile(
    r"""
    ^\s*                       # line start
    """ + RETURN_RE + r"""     # return type
    \s+                        # whitespace
    (?P<name>[A-Za-z_]\w*)     # function name
    \s*\(                      # opening paren of param list
    """,
    re.MULTILINE | re.VERBOSE,
)


def extract_symbols(header_text: str) -> list[str]:
    """Return a sorted, de-duplicated list of function names declared in
    `backend.h`. Skips entries inside `#if 0` / commented-out blocks by
    stripping `//` and `/* ... */` comments first."""
    # Strip block comments.
    text = re.sub(r"/\*.*?\*/", "", header_text, flags=re.DOTALL)
    # Strip line comments.
    text = re.sub(r"//[^\n]*", "", text)
    names = sorted({m.group("name") for m in DECL_RE.finditer(text)})
    # Drop typedefs that the regex incidentally caught (none should
    # match the function-call pattern, but guard anyway).
    EXCLUDE = {"TensorHandle", "TensorPair"}
    return [n for n in names if n not in EXCLUDE]


def render_header(backend: str, symbols: list[str]) -> str:
    """Render the `rename_<backend>.h` content for `backend`."""
    guard = f"IDRISML_RENAME_{backend.upper()}_H"
    lines = [
        f"/* AUTO-GENERATED by scripts/gen-rename-headers.py — DO NOT EDIT. */",
        f"/* Run `make rename-headers` to regenerate after editing backend.h. */",
        f"/* */",
        f"/* Injected via `-include` on backend_{backend}.{ 'c' if backend == 'tape' else 'cpp' } compile.",
        f" * Renames each exported C symbol to `<sym>_{backend}` so all three",
        f" * backends can co-exist linked into one libidrisml.(so|dylib). The",
        f" * primary backend (first item in Makefile's BACKEND list) also gets",
        f" * unified-name aliases via ld -alias_list / -Wl,--defsym so existing",
        f" * Idris %foreign \"C:tensor_add,libidrisml\" declarations keep working",
        f" * unchanged through Phase 1. Phase 2.x then peels each %foreign off",
        f" * into a UserDevice instance method bound to the suffixed name. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        f"",
    ]
    for sym in symbols:
        lines.append(f"#define {sym} {sym}_{backend}")
    lines += [
        f"",
        f"#endif /* {guard} */",
        f"",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if generated content differs from disk.",
    )
    args = parser.parse_args()

    header_text = BACKEND_H.read_text()
    symbols = extract_symbols(header_text)

    print(f"Extracted {len(symbols)} exported symbols from backend.h")

    drift = False
    for backend in BACKENDS:
        out_path = OUT_DIR / f"rename_{backend}.h"
        rendered = render_header(backend, symbols)
        existing = out_path.read_text() if out_path.exists() else ""
        if rendered == existing:
            print(f"  {out_path.name}: unchanged")
            continue
        if args.check:
            print(f"  {out_path.name}: DRIFT (regen would change content)", file=sys.stderr)
            drift = True
            continue
        out_path.write_text(rendered)
        print(f"  {out_path.name}: wrote {len(symbols)} renames")

    if args.check and drift:
        print(
            "\nRename headers are out of date. Run `make rename-headers` and "
            "commit the result.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
